import Head from "next/head";
import React from "react";

const PageLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Mini Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="font-sans">{children}</div>
    </>
  );
};

export default PageLayout;
