import Head from "next/head";
import React from "react";
import { Provider } from "react-redux";
import { persistStore } from "redux-persist";
import { PersistGate } from "redux-persist/integration/react";
import store from "../../../store/store";

let persistor = persistStore(store);

const PageLayout = ({ children }) => {
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <Head>
          <title>Mini Store</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="font-sans">{children}</div>
      </PersistGate>
    </Provider>
  );
};

export default PageLayout;
